### ISSUE TITLE
Try to get a simple Zendro App started on Linux

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/zendro#21]
Follow the [default Zendro manual](https://zendro-dev.github.io/) and set up a new Zendro project on your Linux machine. ✅ 

Use the standard Zendro City, Country, and River models. They should be created automatically. 

Try to use Zendro with and without Docker.

If errors occur, note them down and paste them as comments to this issue below.
Also paste the errors with a request for help in our Slack channel. Particularly @VivianBass is capable of helping you, hopefully.

Should Zendro work, get yourself familiar with:
- Explore the [single page application (SPA) graphical user interface (GUI)](https://zendro-dev.github.io/usage/spa#how-to-use-zendros-graphical-user-interface) ✅
- [GraphiQL](https://zendro-dev.github.io/usage/graphql#graphiql-web-interface) to explore the GraphQL schema and usage in the browser based GraphiQL IDE ✅
- [migrations](https://zendro-dev.github.io/zendro_cli.html#example-for-migrations), e.g. to put in some seed (start) data into your app. ✅ 

Explore Zendro's structure:
- Zendro is a code-generator. For a new model, i.e. a data-model definition in the directory `data_model_definitions` the Zendro CLI generates in the graphql-server a graphql schema, a resolver module, and a data model. In the single page application respective pages are generated. ✅
- understand [their structure](https://zendro-dev.github.io/setup_root/data_models) ✅
- Understand the graphql-server and how GraphQL schemas, and model and resolver modules are generated for each data model ✅

Open issues "up for grabs":
[Here](https://github.com/Zendro-dev/zendro/issues)

Grabbed:
[Issue 17 ](https://www.github.com/Zendro-dev/zendro/issues/17) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/zendro/pull/22) ✅ 
[Issue 32](https://www.github.com/Zendro-dev/graphiql-auth/issues/32) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/graphiql-auth/pull/33) ✅ 
[Issue 24](https://www.github.com/Zendro-dev/zendro/issues/24) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/zendro/pull/25) ✅
[Issue 99](https://www.github.com/Zendro-dev/graphql-server/issues/99) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/graphql-server/pull/100) ✅ 
[Issue 20](https://www.github.com/Zendro-dev/zendro/issues/20) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/zendro/pull/27) ✅
[Issue 138](https://www.github.com/Zendro-dev/single-page-app/issues/138) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/single-page-app/pull/139) ✅

[Issue 219](https://www.github.com/Zendro-dev/graphql-server-model-codegen/issues/219) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/graphql-server-model-codegen/pull/220) ✅ 
[SPA descriptions problem commit](https://www.github.com/Zendro-dev/single-page-app/commit/afbc27ae63a17d537925e5f6fda91c69902487d0)
[Issue 31](https://www.github.com/Zendro-dev/zendro/issues/31) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/zendro/pull/32) ⏳ 
[Issue 4](https://www.github.com/Zendro-dev/zendro-bulk-create/issues/4) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/zendro-bulk-create/pull/5) ⏳ 
[Issue 33](https://www.github.com/Zendro-dev/zendro/issues/33) ✅ $\rightarrow$ [Pull Request](https://www.github.com/Zendro-dev/zendro/pull/34) ⏳ 

[Pull Requests: giql port to 7070](https://github.com/search?q=org%3AZendro-dev%20is%3Apr%20archived%3Afalse%20update%3A%20giql%20uses%20port%207070%20&type=pullrequests) ✅ 

[Pull Requests: AWS Migration to v3](https://github.com/search?q=org%3AZendro-dev+is%3Apr+archived%3Afalse+update%3A+migration+to+aws-sdk+v3&type=pullrequests) ✅

Part of your student-project, issues in descending order or importance:
- Get Zendro running with and without Docker in Linux ✅
- Get Zendro working without Docker on Windows (10/11) ✅ and Mac (with the help of @VivianBass - do pair programming) ✅ 
- Update Zendro's Amazon AWS integration (MinIO) to usage of latest AWS SDK (version 3) ✅

**Comment by asishallab** [comment]
Please write me at the end of each week a _very brief_ report via email of what you have been doing, and how long it took you to do this part, what you managed to finish, what is your next step, and whether you faced certain problems or need help. Request for help as early as possible.

**Comment by qwerdenkerXD** [comment]
An Error when yarn is not installed:

node:events:489
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'install' ]
}

**Comment by qwerdenkerXD** [comment]
An error if you are a creative guy as me and name your project "test", of course there are no default models anymore:

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, lstat '/home/franz/Schreibtisch/zendro/test/data_model_definitions/default'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/franz/Schreibtisch/zendro/test/data_model_definitions/default'
}

**Comment by qwerdenkerXD** [comment]
When using "zendro start -p" for dockerless startup and installed yarn via apt:

Parsing scenario file build
ERROR: [Errno 2] No such file or directory: 'build'
Parsing scenario file start
ERROR: [Errno 2] No such file or directory: 'start'

**Comment by qwerdenkerXD** [comment]
There were also incompatibilities with the versions in graphiql-auth/yarn.lock, when "zendro start -p" for dockerless
I fixed that by removing it and recreated it by "yarn install"

After that there are only a few warnings in the logs and in graphiql-server the error:

/home/franz/Schreibtisch/zendro/without-docker/graphql-server/utils/migration.js:89
      throw Error(err);
            ^

Error: Error: AxiosError: Request failed with status code 401
    at Object.up (/home/franz/Schreibtisch/zendro/without-docker/graphql-server/utils/migration.js:89:13)

**Comment by qwerdenkerXD** [comment]
> There were also incompatibilities with the versions in graphiql-auth/yarn.lock, when "zendro start -p" for dockerless I fixed that by removing it and recreated it by "yarn install"
> 
> After that there are only a few warnings in the logs, but for SPA an error when fetching from zendro-keycloak:
> 
> TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11576:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async refreshAccessToken (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/.next/server/pages/api/auth/[...nextauth].js:159:26) at async Object.session (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next-auth/core/routes/session.js:47:21) at async AuthHandler (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next-auth/core/index.js:165:27) at async NextAuthApiHandler (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next-auth/next/index.js:22:19) at async NextAuth._args$ (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next-auth/next/index.js:106:14) at async Object.apiResolver (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next/dist/server/api-utils/node.js:366:9) at async NextNodeServer.runApi (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next/dist/server/next-server.js:481:9) at async Object.fn (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next/dist/server/next-server.js:741:37) at async Router.execute (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next/dist/server/router.js:252:36) at async NextNodeServer.run (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next/dist/server/base-server.js:365:29) at async NextNodeServer.handleRequest (/home/franz/Schreibtisch/zendro/without-docker/single-page-app/node_modules/next/dist/server/base-server.js:303:20) { cause: Error: getaddrinfo EAI_AGAIN zendro-keycloak at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) { errno: -3001, code: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'zendro-keycloak' } }

Ok, the problem is that zendro does not know what zendro-keycloak means,
so actually I have to replace ALL occurencies of "zendro-keycloak:8080/auth" with "localhost:8081" to get it fixed.
(By the way, [the Guide](https://zendro-dev.github.io/setup_root.html#step-7-start-up-zendro) just says to replace it in graphql-server/.env only)
Found the files by: `find . -type f -name '.env*' -exec grep "zendro-keycloak:8080" \{\} +`

BUT that does not solve the problem, because the downloaded keycloak is not configured for zendro,
so there is no realm called zendro as assumed in URI /realms/zendro, it is "master".
And in the same way a user "zendro_spa" does obviously not exist

**Comment by qwerdenkerXD** [comment]
Ok, it is only a problem with the login. If I start a dockerized project, log into zendro and stop the project, then I am able in my dockerless project to get to the /models page and can add some cities and stuff and query it e.g. via GraphQL. I am able to logout, but after that I'm still not able to log in.

**Comment by asishallab** [comment]
Hello @qwerdenkerXD !

Yes, it seems to be a problem with the login and Keycloak, which we use to manage authentication and authorization. If I read the stack trace correctly, it fails when reading the user roles (in `getRolesFromToken`). Setting up Keycloak is a challenge, especially without Docker where Zendro takes care of everything for you. 

I'd suggest to try the following:
1) Start Zendro "unsafe" without user authentication and authorization ([see parameter `acl`](https://zendro-dev.github.io/setup_root.html#step-8-start-up-zendro-with-access-control)). It should work without ACL, if the problem resides within the authentication and authorization module.
2) Investigate how Keycloak is set up within Docker and try to get an identical set-up done without Docker.
3) Try to the [Keycloak admin interface](https://zendro-dev.github.io/oauth.html#keycloak) to see whether everything is set up correctly. 

P.S.: @wunderbarr and @coeit do you have any ideas?

**Comment by qwerdenkerXD** [comment]
I fixed the graphiql problem by removing the graphiql-auth/yarn.lock

**Comment by qwerdenkerXD** [comment]
Problems in Windows:
`start.js` uses for `giql` wrong scripts, just `yarn dev` or `yarn start`.
Should be done as in `spa` via e.g. `const startScript = process.platform === "win32" ? "start:win" : "start"`

**Comment by qwerdenkerXD** [comment]
Problems in MacOS:
 - since MacOS Monterey Port 7000 may be already in use for the "Airplay Receiver" feature

**Comment by qwerdenkerXD** [comment]
Following error in SPA log when visiting a model page using MinIO as DB in Windows and Linux:
>warn  - ./node_modules/zendro-bulk-create/index.js
Module not found: Can't resolve 'fs' in '/home/franz/Schreibtisch/aws/zendro/aws2/single-page-app/node_modules/zendro-bulk-create'

and in SPA directly Error 200:
>[
     {
          "message": "NoSuchKey: The specified key does not exist.",
          "locations": [
               {
                    "line": 2,
                    "column": 5
               }
          ],
          "path": [
               "countCities"
          ]
     }
]

**Comment by qwerdenkerXD** [comment]
If I configured it correctly, following upload error appears:

>Error: Not supported by Amazon S3
    at city.addOne (/Users/f.sill/Desktop/aws-zendro/projects/aws/graphql-server/models/amazonS3/city.js:317:15)
    at Object.addCity (/Users/f.sill/Desktop/aws-zendro/projects/aws/graphql-server/resolvers/city.js:504:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async graphqlMiddleware (/Users/f.sill/Desktop/aws-zendro/projects/aws/graphql-server/node_modules/express-graphql/index.js:125:26)
{"message":"Not supported by Amazon S3","name":"GraphQLError","originalError":{"message":"Not supported by Amazon S3"},"source":{"body":"mutation{\nn1: addCity(city_id:\"1\",name:\"Berlin\",population:3000000){city_id}\n}","name":"GraphQL request","locationOffset":{"line":1,"column":1}},"positions":[10],"locations":[{"line":2,"column":1}],"path":["n1"],"extensions":{}}

**Comment by qwerdenkerXD** [comment]
Found the problem:
The csv templates are wrong, e.g. in city.csv there is the field `addCountry` instead of `country_id`

**Comment by qwerdenkerXD** [comment]
of course it does not work, in city model:
```
    /**
     * addOne - Not implemented for AmazonS3.
     */
    static async addOne(input) {
        throw new Error('Not supported by Amazon S3');
    }

    /**
     * deleteOne - Delete the whole file.
     */
    static async deleteOne(id) {
        throw new Error('Not supported by Amazon S3');
    }

    /**
     * updateOne - Not implemented for AmazonS3.
     */
    static async updateOne(input) {
        throw new Error('Not supported by Amazon S3');
    }
```

**Comment by qwerdenkerXD** [comment]
Hello @asishallab,
thanks for the answer. I already realized this. But it is still confusing since there are upload and download buttons in spa.

**Comment by qwerdenkerXD** [comment]
After migrating the code to v3, gqs can't connect to MinIO:
>ERROR: Time out reached while waiting for database connections to be available.

I figured out where it happens:
>TypeError: instance.connection.waitFor is not a function
    at exports.checkConnections (/home/franz/Desktop/aws-upgrade/t1/graphql-server/connection.js:238:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runCheck (/home/franz/Desktop/aws-upgrade/t1/graphql-server/scripts/testDatabaseConnectionsAvailable.js:26:22)
